basePath: /api/v1
definitions:
  beat.BeatCreateDTO:
    properties:
      beatType:
        type: string
      key:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /beats:
    get:
      description: create beat
      responses: {}
      tags:
      - beats
    post:
      description: create beat
      parameters:
      - description: 생성하려는 파일의 key와 beatType 를 넣어주세요.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/beat.BeatCreateDTO'
      responses: {}
      tags:
      - beats
  /beats/presigned-url/put:
    post:
      description: create presigned url to upload beats (m4a audio file)
      responses: {}
      tags:
      - beats
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
