package main

import (
	"log"

	"github.com/JanSound/10Seconds-backend-go/beat"
	docs "github.com/JanSound/10Seconds-backend-go/docs"
	swaggerFiles "github.com/swaggo/files"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	ginSwagger "github.com/swaggo/gin-swagger"
	// docs is generated by Swag CLI, you have to import it.
)

func main() {

	// .env 파일을 읽어서 환경변수를 설정
	docs.SwaggerInfo.BasePath = ""
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env5 file")
	}

	r := gin.Default()

	r.GET("/generate-presigned-url", beat.GeneratePresignedURL)

	// Swagger

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8001")
}
